spring:
  application:
    name: spb3-service-1
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: development
  cloud:
    config:
      fail-fast: true # If set to true, the application will fail to start if there is an error in the configuration server.
      username: mySuperUserName
      password: mySuperPassword
  security: ## User and password to access to the service 1
    user:
      name: myService1UserName
      password: myService1Password
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.jesusfc.demo.kafka.message.OrderCreated

# Basic authentication for the service 2
feign:
  client-service-2:
    username: myService2UserName
    password: myService2Password